<?php

/**
 * Created by PhpStorm.
 * User: moohii07
 * Date: 01.11.2017
 * Time: 11:17
 */

namespace app\widgets;

use yii\base\Widget;
use app\models\Category;
use yii\helpers\Url;
use Yii;

class CategoriesWidget extends Widget
{
    public $type;
    public $data;
    public $menuHtml;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        switch($this->type){
            case 'categories':
                $this->type = 'categories';
                break;
            case 'shops':
                $this->type = 'shops';
                break;
            case 'manufacture':
                $this->type = 'manufacture';
                break;
        }

    }

    public function run(){

        $menu = Yii::$app->cache->get($this->type);
        if($menu) return $menu;

        switch($this->type){
            case 'categories':
                $this->data = Category::find()->where(['parent' => 0, 'active' => 1])->orderBy(['name' => SORT_ASC])->asArray()->all();
                $this->type = 'categories';
                break;
        }

        $this->menuHtml .= '<ul class="dropdown-menu">';
        if($this->type != 'categories'){
            foreach($this->data as $cat){
                $this->menuHtml .= '<li>'.'<a href='.Url::to(["$this->type/index" , 'alias' => $cat['alias']]) .'>'. $cat['name']. '</a></li>';
            }
        }else{
            foreach($this->data as $cat){
                $this->menuHtml .= '<li>'.'<a href='.Url::to(["$this->type/view" , 'alias' => $cat['alias']]) .'>'. $cat['name']. '</a></li>';
            }
        }
        if($this->type == 'categories'){
            $this->menuHtml .= '<li role="separator" class="divider"></li>'.
                '<li>'.'<a href='.Url::to(["$this->type/index"]) .'>Показать все</a></li>';

        }
        $this->menuHtml .='</ul>';

        Yii::$app->cache->set($this->type, $this->menuHtml, 60);
        return $this->menuHtml;
    }

}