<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tk_subscription".
 *
 * @property integer $id
 * @property string $name
 * @property integer $active
 * @property string $price
 * @property string $old_price
 * @property string $information
 *
 * @property TkSubscriptionEventLink[] $tkSubscriptionEventLinks
 * @property TkUserSubscription[] $tkUserSubscriptions
 */
class Subscription extends \yii\db\ActiveRecord
{
    /**
     * This is main image for subscription
     * @var $image
     */
    public $image;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tk_subscription';
    }

    public function behaviors()
    {
        return [
            'image' => [
                'class' => 'rico\yii2images\behaviors\ImageBehave',
            ]
        ];
        //return parent::behaviors(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'information'], 'required'],
            [['active'], 'integer'],
            [['price', 'old_price'], 'number'],
            [['information', 'image'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique']
        ];
        /*
        return [
            [['name', 'information'], 'required'],
            [['active'], 'integer'],
            [['price', 'old_price'], 'number'],
            [['information'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique'],
            [['image'],'file', 'extensions' => 'png, jpg, jpeg']
        ];
        */
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'image' => 'Main image',
            'active' => 'Active',
            'price' => 'Price',
            'old_price' => 'Old Price',
            'information' => 'Information',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTkSubscriptionEventLinks()
    {
        return $this->hasMany(TkSubscriptionEventLink::className(), ['id_subscription' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTkUserSubscriptions()
    {
        return $this->hasMany(TkUserSubscription::className(), ['id_subscription' => 'id']);
    }

    public function upload_image(){
        if($this->custom_validate($this->image)){
            $this->attachImage($this->image, true);
            return true;
        }else{
            return false;
        }
    }

    private function custom_validate($file)
    {
        if (file_exists($file) && getimagesize($file)) {
            return true;
        } else {
            die('error download file');
        }
    }
}
